### ISSUE TITLE
Unknown layers popup in Eagle

### ISSUE THREAD

**Issue by 1am** [fxkr/eagle-diff#14]
Hi

First of all thanks for the project. It's awesome.
After finding https://github.com/fxkr/eagle-diff/issues/5 I've quickly configured it to do a diff of my last changes. But one thing is bothering me as during image export Eagle shows me a bunch of "Unknown layer: X" messages. The unknown layers are: 2, 3, 14, 15, 2, 3, 14, 15 for each file opened - this is the order of error messages. I don't have the layers on my project and I've never had as I'm working with the Eagle's defaults. Is there a way to exclude some layers from the diff without modyfying the python script? I've seen the LAYER_NAMES dict in the script.

I'm working on OSX 10.9, Eagle 6.6.0.

PB

**Comment by fxkr** [comment]
Hi! I'm really sorry I didn't reply sooner! I completely missed the notification. I'm happy that you find eagle-diff useful.

When you create a board with the free version of eagle, it only creates layers 2-15. The paid version creates all layers (and sets `active="no"` on layer 2-15 so they won't show up in the layer list). It should be relatively easy to detect which layers are available in Python. I really should implement that.

I don't know what causes the warning, but I guess that'll go away once I've managed to get Eagle to not complain about the missing layers anymore. (I could redirect all of Eagles output to nowhere, but...).

**Comment by 1am** [comment]
Great! I'll check this out next time I'm using your project.
I'm using the basic (paid) version of Eagle. It's similar to the free one, except it costs money :)
